# https://docs.travis-ci.com/user/languages/perl/
# also: https://github.com/mjgardner/svn-simple-hook/blob/master/.travis.yml for dzil
language: perl
perl:
  - blead
  - dev
#  No clean build due to removal of '.' from lib path
#  - 5.26
  - 5.24
  - 5.22
  - 5.20
  - 5.18
  - 5.16
  - 5.14
  - 5.12
  - 5.10
#  stopping builds; is anyone really still using this version?
#  - 5.8
matrix:
  include:
    - perl: 5.24
      env: COVERAGE=1
  allow_failures:
    - perl: blead
    - perl: blead-thr
sudo: false
env:
  global:
    - RELEASE_TESTING=1
    - AUTHOR_TESTING=1
before_install:
    - cpanm -v Pod::Elemental::Transformer::List 
    - perldoc -lm Pod::Elemental::Transformer::List
    - eval $(curl https://travis-perl.github.io/init) --auto
#    - "cpanm -v Dist::Zilla"
##    - "cpanm Dist::Zilla::Plugin::MakeMaker::Awesome" # not required for this module
#    - "cpanm Pod::Weaver::Plugin::StopWords"
#    - "cpanm Pod::Weaver::Section::Support"
#    # needed for DZP::GitHub
#    - "git config --global github.user duncs"
#    # install dist development dependencies
#    - "dzil authordeps | xargs cpanm"
#    - "export tmpbuild=`mktemp --directory`"
#    - "dzil build --in $tmpbuild"
#    - "perl -MCPAN::Meta -e '$,=\"\\n\"; print CPAN::Meta->load_file(\"$ENV{tmpbuild}/META.json\")->effective_prereqs->requirements_for(\"develop\", \"requires\")->required_modules' | xargs cpanm"
install: "dzil listdeps | xargs cpanm"
script: "dzil test --release"

